[build]
  command = "pnpm run build-docker"
  publish = ".next"

[functions]
  directory = ".netlify/functions"
  included_files = ["node_modules/.geo/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
